name: fstma-tut04
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python=3.8
  - scikit-learn
  - matplotlib
  - tqdm
  - ipywidgets
  - git
  - pip
  - pip:
    - pettingzoo[mpe]
    - git+https://github.com/sarah-keren/multi-taxi
    - pygame
    - git+https://github.com/sarah-keren/AI_agents