name: fstma-tut08
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - ca-certificates
  - openssl
  - git
  - pip
  - pip:
    - git+https://github.com/sarah-keren/multi_taxi
    - git+https://github.com/sarah-keren/AI_agents
