name: fstma-tut03
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python=3.8
  - tqdm
  - ipywidgets
  - git
  - pip
  - pip:
    - pettingzoo[mpe]
    - git+https://github.com/sarah-keren/AI_agents