name: fstma-tut03
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python=3.8
  - scikit-learn
  - pytorch
  - matplotlib
  - tensorboard
  - torchvision
  - tqdm
  - ipywidgets
  - git
  - pip
  - pip:
    - pettingzoo[mpe]
    - git+https://github.com/sarah-keren/AI_agents